### PR TITLE
add hw1

### PR DESCRIPTION
**Pull request by joyceiphone**
Please review my code.

### CODE REVIEW

**Comment by chuxu200328** [comment]
image
font too small

**Comment by chuxu200328** [comment]
image
not an the center

**Comment by chuxu200328** [comment]
image
wrong size

**Comment by chuxu200328** [comment]
image

**Comment by chuxu200328** [comment]
image
wrong style

**Comment by chuxu200328** [comment]
too high
image

**Comment by chuxu200328** [comment]
image
icon too small

**Comment by chuxu200328** [comment]
image
wrong style

**Comment by chuxu200328** [comment]
image
remove this big gap

**Comment by joyceiphone** [comment]
I changed the code. Please review.

**Comment by chuxu200328** [comment]
image
this button still need to fix

**Comment by chuxu200328** [comment]
I think you just fix the first page, the rest of the homework you still need to fix.

**Pull request closed without merging**
