### PR TITLE
Joyceweek3

### PR DESCRIPTION
**Pull request by joyceiphone**
Original git push for week3 assignment failed. I switched to another branch to upload the hw.

### CODE REVIEW

**Comment by chuxu200328** [comment]
image

**Comment by chuxu200328** [comment]
image
should be center

**Comment by chuxu200328** [comment]
image
not at the center

**Comment by chuxu200328** [comment]
image
wrong icon
go to https://fontawesome.com/

**Comment by chuxu200328** [comment]
image

**Comment by joyceiphone** [comment]
你好,在自己的浏览器看qq和taobao网页是居中的.

**Comment by joyceiphone** [comment]
changed saturn

**Pull request closed without merging**
