### PR TITLE
Haixin

### PR DESCRIPTION
**Pull request by haixin7**
Hi

### CODE REVIEW

**Comment by chuxu200328** [comment]
image
The width of this block is too large. It should shorter like this:
image

**Comment by chuxu200328** [comment]
image
Navbar has the same problem
image

**Comment by chuxu200328** [comment]
image
The top part of this page is not at the right position

**Comment by chuxu200328** [comment]
image

The navbar of this page also has the width problem

image

**Comment by chuxu200328** [comment]
image
"password" should be lowercase.

**Comment by chuxu200328** [comment]
Fix this 
image
image

**Comment by chuxu200328** [comment]
image

**Comment by chuxu200328** [comment]
image

**Comment by haixin7** [comment]
revised

**Pull request closed without merging**
